policies:
  - type: commit
    spec:
      header:
        lenght: 90
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          [
            "chore",
            "docs",
            "perf",
            "refactor",
            "style",
            "test",
            "release",
            "ci",
            "feat",
            "fix",
            "build",
          ]
        scopes: [".*"]
