[package]
name = "sync-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
securestore = "0.100.0"
surrealdb = "1.0.0"
surreal-id = "0.2.1"
once_cell = "1.18.0"
ractor = "0.9"
tokio = { version = "1.0.0", features = ["full"] }
futures = "0.3.29"
uuid = "1.5.0"
warp = "0.3.6"
figment = { version = "0.10.12", features = ["toml"] }
async-trait = "0.1.74"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
hyper = { version = "1", features = ["full"] }
serde = { version = "1.0.192", features = ["derive"] }
typetag = "0.2.13"
serde_repr = "0.1.17"
env_logger = "0.10.1"
log = "0.4.20"
futures-util = "0.3.29"
tokio-stream = "0.1.14"
serde_json = { version = "1.0.108", features = ["raw_value"] }
chrono = "0.4.31"
hashbrown = "0.14.3"
