[package]
name = "sync-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surrealdb = "1.0.0"
serde = "1.0.192"
once_cell = "1.18.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.29"
uuid = "1.5.0"
chrono = "0.4.31"
warp = "0.3.6"
