[database]
endpoint = "rocksdb://storage"
namespace = "default"
database = "default"

[secrets]
key = "secrets.key"
path = "secrets.json"

[mqtt]
id = 0

[mqtt.router]
id = 0
max_connections = 10010
max_outgoing_packet_count = 200
max_segment_size = 104857600
max_segment_count = 10

[mqtt.v5.1]
name = "v5-1"
listen = "0.0.0.0:1884"
next_connection_delay_ms = 1

[mqtt.v5.1.connections]
connection_timeout_ms = 60000
max_payload_size = 20480
max_inflight_count = 100
