[devshell]
name = "sync"
packages = ["cargo-make"]

[[commands]]
name = "check"
help = "Runs all the checks for code standard"
category = "project"
command = "cargo make check"

[[commands]]
name = "run"
help = "Starts the project"
category = "project"
command = "cargo run"

[[commands]]
name = "setup"
help = "Prepares the project for development"
category = "project"
command = "cargo make setup"
