[tasks.cargo-upgrade]
private = true
command = "cargo"
args = ["upgrade", "--pinned"]

[tasks.cargo-update]
private = true
command = "cargo"
args = ["update"]

[tasks.cargo-fmt]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.cargo-audit]
command = "cargo"
args = ["audit"]

[tasks.cargo-clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.generate-secrets]
install_crate = { crate_name = "ssclient", force = true }
command = "ssclient"
args = ["--no-vcs", "create", "secrets.json", "--export-key", "secrets.key"]

[tasks.generate-config]
command = "cp"
args = ["config.example.json5", "config.json5"]

[tasks.setup]
category = "Local commands"
dependencies = [
    "cargo-upgrade",
    "cargo-update",
    "generate-config",
    "generate-secrets",
    "check",
]

[tasks.clean]
category = "Local commands"
command = "cargo"
args = ["clean"]

[tasks.check]
category = "Local commands"
dependencies = ["cargo-fmt", "cargo-audit", "cargo-clippy"]
