name: "CI"
on: [push, pull_request]
jobs:
    precheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Commits safety
              uses: siderolabs/conform@v0.1.0-alpha.27
              with:
                token: "${{ secrets.GITHUB_TOKEN }}"