name: "CI"
on: [pull_request, merge_group]
jobs:
    commits:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - uses: oven-sh/setup-bun@v1

            - name: Install commit lint
              run: bun install commitlint@latest | bun install @commitlint/config-conventional@latest
      
            - name: Validate PR commits with commitlint
              run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose