name: "CI"
on: [pull_request, merge_group]
jobs:
    commits:
      name: Check commits standard
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      steps:
        - name: Checkout sources
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Install bun
          uses: oven-sh/setup-bun@v1

        - name: Install commit lint
          run: bun install commitlint@latest | bun install @commitlint/config-conventional@latest
      
        - name: Validate PR commits with commitlint
          run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

    format:
      name: Check format
      runs-on: ubuntu-latest
      if: github.event_name == 'merge_group'
      steps:
        - name: Install stable toolchain
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
            components: rustfmt

        - name: Checkout sources
          uses: actions/checkout@v4

        - name: Setup cache
          uses: Swatinem/rust-cache@v2
          with:
            save-if: ${{ github.ref == 'refs/heads/main' }}

        - name: Install cargo-make
          run: cargo install --debug --locked cargo-make

        - name: Check format
          run: cargo make ci-format

    check:
      name: Check workspace
      runs-on: ubuntu-latest
      if: github.event_name == 'merge_group'
      steps:
        
        - name: Install stable toolchain
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        
        - name: Checkout sources
          uses: actions/checkout@v4

        - name: Setup cache
          uses: Swatinem/rust-cache@v2
          with:
            save-if: ${{ github.ref == 'refs/heads/main' }}
        
        - name: Install cargo-make
          run: cargo install --debug --locked cargo-make
        
        - name: Check workspace
          run: cargo make ci-check