name: "CI"
on: [push, pull_request]
jobs:
    commits:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1

            - name: Install commit lint
              run: bun install commitlint@latest
            
            - name: Validate current commit (last commit)
              if: github.event_name == 'push'
              run: bunx commitlint --from HEAD~1 --to HEAD --verbose
      
            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose